Meta and likes added
bagdenia/react pull request #2
Opened 2017-11-02 13:34 UTC by bagdenia

2017-11-02 22:12 UTC, index01d requested changes
нужно поработать со стилистикой в коде, привести все к единообразию и порядку, иначе в следующем уроке можно будет запутаться.

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +  { count: 5, date_crtd: moment().add(-1, 'days').format('DD-MM-YYYY'), text: 'number' },
1) не жадничай строчки и буквы в названиях:) разбей пожалуйста свойства на строки.

2) В JS чаще всего принято использовать camelCase в именованиях: `dateCreated`, а не в snake_case

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +  { count: 5, date_crtd: moment().add(-1, 'days').format('DD-MM-YYYY'), text: 'number' },
чтобы не дублировать формат даты, лучше вынести форматирование в нужный формат в отдельную функцию

```
const formatDate = (date) => moment(date).format('DD-MM-YYYY')
```
и использовать его на месте

```{
  dateCreated: formatDate(...)
}```

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +  { name: 'Fedya', src: 'https://pp.userapi.com/c639828/v639828889/58af6/wrl1B46fCuE.jpg' },
лучше выделить вложенный объект image и вынести туда все, что касается картинки, тогда не будут перемешиваться значения для картинки и для поста
```
{
  name: 'Fedya',
  text: 'number',
  image: {
    src: 'https://pp.userapi.com/c639828/v639828889/58af6/wrl1B46fCuE.jpg'
  },
  meta: {
    likes: 5,
    dateCreated: formatDate('2017-10-092')
  }
}
```

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +  <img src = { src } height = { height } width = {width } alt = { alt ? alt + ind : `img${ ind }` } />
1) аттрибуты можно также разбить на строчки, чтобы код был читабельнее, хотелось бы чтобы альт был задан в исходном списке постов. 

2) Зачем сюда передается index?

3) Опять же не надо жадничать буквы:) и нужно аккуратнее расставлять пробелы `{width }`, здесь явно лишний

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +    text != 'test' ? text : 'SuperTest'
здесь лучше использовать свойство children, наличие тут условия не выглядит оправданным

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +const Metax = ({name, date_crtd, date_upd}) => (
почему Metax, а не Meta? нужно использовать camelCase в названиях свойств, в списке свойств в сигнатуре не хватает пробелов после открывающейся и перед закрывающейся фигурной скобкой

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +    `Created by ${ name } at ${ date_crtd }, last modified at ${ date_upd }`)
здесь пробелы при интерполяции наоборот стилистически не приняты и являются лишними

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +     <span>Count: {this.state.count}</span>
почему-то тут нет пробелов

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +     <button onClick={ this.handleLike }> Like </button>
а тут есть, хотя и не должно быть, не совсем ясно зачем пробелы в строчке Like

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +    React.createElement(Metax,
нужно либо не переносить аргументы, либо переносить оба аргумента функции

2017-11-02 22:12 UTC, index01d commented on lesson1/blogpage.js
> +        React.createElement(BlogItem, {meta: { name: item.name,
здесь уже новый стиль переносов, нужно привести к единообразию

2017-11-03 10:50 UTC, bagdenia commented on lesson1/blogpage.js
> +  <img src = { src } height = { height } width = {width } alt = { alt ? alt + ind : `img${ ind }` } />
index просто поиграться, добавляла его к alt

2017-11-04 06:49 UTC, index01d approved these changes

2017-11-13 10:26 UTC, merged